version: "3.7"
services:
  backend:
    image: demeter-api:latest
    build:
      context: .
    container_name: demeter-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://my_user:my_password@db:5432/my_db
    volumes:
      - ./src:/app
    command: sh -c "uvicorn app:app --host 0.0.0.0 --reload"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./database/.
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: