import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  sprint1Side: [{ type: "autogenerated", dirName: "Sprint 1" }],
  sprint2Side: [{ type: "autogenerated", dirName: "Sprint 2" }],
  sprint3Side: [{ type: "autogenerated", dirName: "Sprint 3" }],
  sprint4Side: [{ type: "autogenerated", dirName: "Sprint 4" }],
  sprint5Side: [{ type: "autogenerated", dirName: "Sprint 5" }],

};

export default sidebars;
